from unittest import IsolatedAsyncioTestCase
from pyppeteer import launch

from c_scraper import coriolis_scrape


class TestCoriolisScraper(IsolatedAsyncioTestCase):
    async def launch_browser(self) -> None:
        self.browser = await launch()
        self.page = await self.browser.newPage()

    async def close_browser(self) -> None:
        await self.browser.close()

    async def test_coriolisScraper_assigns_link(self) -> None:
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        self.assertEqual('https://s.orbis.zone/lgzu',
                         self.coriolisScraper.link)

    async def test_browser_opens_page(self) -> None:
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        # call method that gets the web page
        await self.coriolisScraper.openPage()
        self.assertIn('EasyChief', self.coriolisScraper.pageTitle)

    async def test_browser_can_opened_correct_page(self) -> None:
        await self.launch_browser()
        # Open link of a coriolis ship build and check the correct page
        # is opened.
        await self.page.goto(url='https://s.orbis.zone/lgzu')
        self.pageTitle: str = await self.page.title()
        self.assertIn('EasyChief', self.pageTitle)

    async def test_materials_button_was_rendered(self) -> None:
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        # call the method that identifies the button that generates
        # materials in json
        await self.coriolisScraper.getButton()
        self.assertIsNotNone(self.coriolisScraper.materialsButton)

    async def test_scraper_can_click_button(self) -> None:
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        # Click the button
        await self.coriolisScraper.clickButton()

    async def test_scraper_can_extract_materials_data(self) -> None:
        '''Check that the scraper can extract text that contains list
        of materials generated by Coriolis.
        '''
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        # Generate materials
        await self.coriolisScraper.getMaterialsHTMLElement()
        self.assertIsNotNone(self.coriolisScraper.materialsHTMLElement)

    async def test_scraper_can_extract_materials_as_text(self) -> None:
        '''Check that after button click a textarea HTML element is
        rendered and contains text.
        '''
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        # Check for materials text in innerHTML
        await self.coriolisScraper.getMaterials()
        self.assertIsNotNone(self.coriolisScraper.materialsAsText)

    async def test_scraper_can_extract_experimental_mod_materials(self) -> None:
        '''Check that the scraper can get the raw json for materials for
        experimental mods.
        '''
        self.coriolisScraper = coriolis_scrape.CoriolisScraper(
            'https://s.orbis.zone/lgzu')

        await self.coriolisScraper.getRawExperimentalsMaterials()
        self.assertIsNotNone(self.coriolisScraper.rawExperimentalsMaterials)
